# Generated by Django 5.2.7 on 2025-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=50, verbose_name='Nombre')),
                ('subnombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre Corto')),
                ('activo', models.BooleanField(default='false', verbose_name='Anulado')),
            ],
        ),
    ]
