# Generated by Django 5.2.7 on 2025-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['-nombre'], 'verbose_name': 'Mi departamento', 'verbose_name_plural': 'Áreas de la empresa'},
        ),
        migrations.AlterField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'subnombre')},
        ),
    ]
