# Generated by Django 5.2.7 on 2025-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
